// Generated by the return's measuring script (README, "The density"):
// Playwright on these very screens, CSS pixels, viewports 1280 × 900 and
// 390 × 844. "stacked" is the counterfactual the side selector avoids:
// both sides on one board. Do not edit by hand.
export const MEASURES = {
  "en1280": {
    "demand": {
      "board": 4767,
      "blocks": 11,
      "controls": 34,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": 884,
      "total": 214,
      "money": 626,
      "funnel": 703,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supply": {
      "board": 4922,
      "blocks": 11,
      "controls": 30,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": 884,
      "total": 214,
      "money": 644,
      "funnel": 797,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supplyNoSubs": {
      "board": 3393,
      "blocks": 9,
      "controls": 23,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)",
        "Demand",
        "Supply"
      ],
      "primaryTop": 437,
      "selectorTop": 638,
      "total": null,
      "money": 230,
      "funnel": 842,
      "raised": 1,
      "primaries": 1,
      "reds": 0
    },
    "demandNoSubs": {
      "board": 4272,
      "blocks": 10,
      "controls": 29,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)",
        "Demand",
        "Supply"
      ],
      "primaryTop": 437,
      "selectorTop": 638,
      "total": null,
      "money": 626,
      "funnel": 703,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "stacked": {
      "board": 7189,
      "blocks": 17,
      "controls": 36,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": null,
      "total": 214,
      "money": 626,
      "funnel": 703,
      "raised": 2,
      "primaries": 1,
      "reds": 8
    }
  },
  "en1280-services": {
    "demand": {
      "board": 4789,
      "blocks": 11,
      "controls": 34,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": 884,
      "total": 214,
      "money": 626,
      "funnel": 703,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supply": {
      "board": 4922,
      "blocks": 11,
      "controls": 30,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": 884,
      "total": 214,
      "money": 644,
      "funnel": 797,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supplyNoSubs": {
      "board": 3393,
      "blocks": 9,
      "controls": 23,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)",
        "Demand",
        "Supply"
      ],
      "primaryTop": 437,
      "selectorTop": 638,
      "total": null,
      "money": 230,
      "funnel": 842,
      "raised": 1,
      "primaries": 1,
      "reds": 0
    },
    "demandNoSubs": {
      "board": 4293,
      "blocks": 10,
      "controls": 29,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)",
        "Demand",
        "Supply"
      ],
      "primaryTop": 437,
      "selectorTop": 638,
      "total": null,
      "money": 626,
      "funnel": 703,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "stacked": {
      "board": 7211,
      "blocks": 17,
      "controls": 36,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": null,
      "total": 214,
      "money": 626,
      "funnel": 703,
      "raised": 2,
      "primaries": 1,
      "reds": 8
    }
  },
  "en390": {
    "demand": {
      "board": 5861,
      "blocks": 11,
      "controls": 34,
      "firstScreen": 3,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →"
      ],
      "primaryTop": 851,
      "selectorTop": 1095,
      "total": 392,
      "money": 806,
      "funnel": 1058,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supply": {
      "board": 5804,
      "blocks": 11,
      "controls": 30,
      "firstScreen": 3,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →"
      ],
      "primaryTop": 851,
      "selectorTop": 1095,
      "total": 392,
      "money": 759,
      "funnel": 987,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supplyNoSubs": {
      "board": 3749,
      "blocks": 9,
      "controls": 23,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)",
        "Demand",
        "Supply"
      ],
      "primaryTop": 433,
      "selectorTop": 677,
      "total": null,
      "money": 317,
      "funnel": 816,
      "raised": 1,
      "primaries": 1,
      "reds": 0
    },
    "demandNoSubs": {
      "board": 5132,
      "blocks": 10,
      "controls": 29,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)",
        "Demand",
        "Supply"
      ],
      "primaryTop": 433,
      "selectorTop": 677,
      "total": null,
      "money": 806,
      "funnel": 1058,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "stacked": {
      "board": 8603,
      "blocks": 17,
      "controls": 36,
      "firstScreen": 3,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →"
      ],
      "primaryTop": 851,
      "selectorTop": null,
      "total": 392,
      "money": 806,
      "funnel": 1058,
      "raised": 2,
      "primaries": 1,
      "reds": 8
    }
  },
  "en390-services": {
    "demand": {
      "board": 5856,
      "blocks": 11,
      "controls": 34,
      "firstScreen": 3,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →"
      ],
      "primaryTop": 851,
      "selectorTop": 1095,
      "total": 392,
      "money": 780,
      "funnel": 1080,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supply": {
      "board": 5804,
      "blocks": 11,
      "controls": 30,
      "firstScreen": 3,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →"
      ],
      "primaryTop": 851,
      "selectorTop": 1095,
      "total": 392,
      "money": 759,
      "funnel": 987,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supplyNoSubs": {
      "board": 3749,
      "blocks": 9,
      "controls": 23,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)",
        "Demand",
        "Supply"
      ],
      "primaryTop": 433,
      "selectorTop": 677,
      "total": null,
      "money": 317,
      "funnel": 816,
      "raised": 1,
      "primaries": 1,
      "reds": 0
    },
    "demandNoSubs": {
      "board": 5127,
      "blocks": 10,
      "controls": 29,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →",
        "Save (.json)",
        "Demand",
        "Supply"
      ],
      "primaryTop": 433,
      "selectorTop": 677,
      "total": null,
      "money": 780,
      "funnel": 1080,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "stacked": {
      "board": 8599,
      "blocks": 17,
      "controls": 36,
      "firstScreen": 3,
      "firstScreenLabels": [
        "Settings",
        "Engine, month and file",
        "Prepare your slides →"
      ],
      "primaryTop": 851,
      "selectorTop": null,
      "total": 392,
      "money": 780,
      "funnel": 1080,
      "raised": 2,
      "primaries": 1,
      "reds": 8
    }
  },
  "fr1280": {
    "demand": {
      "board": 4871,
      "blocks": 11,
      "controls": 34,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": 884,
      "total": 214,
      "money": 644,
      "funnel": 725,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supply": {
      "board": 4940,
      "blocks": 11,
      "controls": 30,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": 884,
      "total": 214,
      "money": 661,
      "funnel": 797,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supplyNoSubs": {
      "board": 3416,
      "blocks": 9,
      "controls": 23,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)",
        "Demande",
        "Offre"
      ],
      "primaryTop": 437,
      "selectorTop": 638,
      "total": null,
      "money": 253,
      "funnel": 842,
      "raised": 1,
      "primaries": 1,
      "reds": 0
    },
    "demandNoSubs": {
      "board": 4375,
      "blocks": 10,
      "controls": 29,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)",
        "Demande",
        "Offre"
      ],
      "primaryTop": 437,
      "selectorTop": 638,
      "total": null,
      "money": 644,
      "funnel": 725,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "stacked": {
      "board": 7310,
      "blocks": 17,
      "controls": 36,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": null,
      "total": 214,
      "money": 644,
      "funnel": 725,
      "raised": 2,
      "primaries": 1,
      "reds": 8
    }
  },
  "fr1280-services": {
    "demand": {
      "board": 4871,
      "blocks": 11,
      "controls": 34,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": 884,
      "total": 214,
      "money": 644,
      "funnel": 725,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supply": {
      "board": 4979,
      "blocks": 11,
      "controls": 30,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": 884,
      "total": 214,
      "money": 679,
      "funnel": 797,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supplyNoSubs": {
      "board": 3482,
      "blocks": 9,
      "controls": 23,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)",
        "Demande",
        "Offre"
      ],
      "primaryTop": 437,
      "selectorTop": 638,
      "total": null,
      "money": 253,
      "funnel": 842,
      "raised": 1,
      "primaries": 1,
      "reds": 0
    },
    "demandNoSubs": {
      "board": 4375,
      "blocks": 10,
      "controls": 29,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)",
        "Demande",
        "Offre"
      ],
      "primaryTop": 437,
      "selectorTop": 638,
      "total": null,
      "money": 644,
      "funnel": 725,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "stacked": {
      "board": 7350,
      "blocks": 17,
      "controls": 36,
      "firstScreen": 4,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)"
      ],
      "primaryTop": 683,
      "selectorTop": null,
      "total": 214,
      "money": 644,
      "funnel": 725,
      "raised": 2,
      "primaries": 1,
      "reds": 8
    }
  },
  "fr390": {
    "demand": {
      "board": 6127,
      "blocks": 11,
      "controls": 34,
      "firstScreen": 2,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier"
      ],
      "primaryTop": 900,
      "selectorTop": 1144,
      "total": 418,
      "money": 865,
      "funnel": 1125,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supply": {
      "board": 6020,
      "blocks": 11,
      "controls": 30,
      "firstScreen": 2,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier"
      ],
      "primaryTop": 900,
      "selectorTop": 1144,
      "total": 418,
      "money": 852,
      "funnel": 1002,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supplyNoSubs": {
      "board": 3834,
      "blocks": 9,
      "controls": 23,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)",
        "Demande",
        "Offre"
      ],
      "primaryTop": 457,
      "selectorTop": 700,
      "total": null,
      "money": 340,
      "funnel": 831,
      "raised": 1,
      "primaries": 1,
      "reds": 0
    },
    "demandNoSubs": {
      "board": 5349,
      "blocks": 10,
      "controls": 29,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)",
        "Demande",
        "Offre"
      ],
      "primaryTop": 457,
      "selectorTop": 700,
      "total": null,
      "money": 865,
      "funnel": 1125,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "stacked": {
      "board": 8956,
      "blocks": 17,
      "controls": 36,
      "firstScreen": 2,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier"
      ],
      "primaryTop": 900,
      "selectorTop": null,
      "total": 418,
      "money": 865,
      "funnel": 1125,
      "raised": 2,
      "primaries": 1,
      "reds": 8
    }
  },
  "fr390-services": {
    "demand": {
      "board": 6071,
      "blocks": 11,
      "controls": 34,
      "firstScreen": 2,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier"
      ],
      "primaryTop": 900,
      "selectorTop": 1144,
      "total": 418,
      "money": 865,
      "funnel": 1125,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supply": {
      "board": 6104,
      "blocks": 11,
      "controls": 30,
      "firstScreen": 2,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier"
      ],
      "primaryTop": 900,
      "selectorTop": 1144,
      "total": 418,
      "money": 852,
      "funnel": 1060,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "supplyNoSubs": {
      "board": 3895,
      "blocks": 9,
      "controls": 23,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)",
        "Demande",
        "Offre"
      ],
      "primaryTop": 457,
      "selectorTop": 700,
      "total": null,
      "money": 340,
      "funnel": 888,
      "raised": 1,
      "primaries": 1,
      "reds": 0
    },
    "demandNoSubs": {
      "board": 5292,
      "blocks": 10,
      "controls": 29,
      "firstScreen": 6,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier",
        "Prépare tes slides →",
        "Enregistrer (.json)",
        "Demande",
        "Offre"
      ],
      "primaryTop": 457,
      "selectorTop": 700,
      "total": null,
      "money": 865,
      "funnel": 1125,
      "raised": 1,
      "primaries": 1,
      "reds": 5
    },
    "stacked": {
      "board": 9018,
      "blocks": 17,
      "controls": 36,
      "firstScreen": 2,
      "firstScreenLabels": [
        "Réglages",
        "Moteur, mois et fichier"
      ],
      "primaryTop": 900,
      "selectorTop": null,
      "total": 418,
      "money": 865,
      "funnel": 1125,
      "raised": 2,
      "primaries": 1,
      "reds": 8
    }
  }
};
