// Generated by the return's measuring script (README, "How the measures were
// taken"): Playwright on these very screens, CSS pixels, viewports 1280 × 900
// and 390 × 844, English unless the key ends in "fr". Do not edit by hand.
export const MEASURES = {
  "firstToolAt1280": 735,
  "firstToolAt390": 956,
  "firstToolAt1280fr": 732,
  "firstToolAt390fr": 953,
  "startControls": 7,
  "startHeight1280": 618,
  "startHeight390": 781,
  "returnToolAt1280": 287,
  "returnToolAt390": 288,
  "returnToolAt1280fr": 287,
  "returnToolAt390fr": 288,
  "returnFirstControls1280": 5,
  "returnFirstControls390": 3,
  "returnPrimaryBottom1280": 768,
  "returnPrimaryBottom390": 788,
  "returnPrimaryBottom390fr": 812,
  "boardControls": 27,
  "boardHeight1280": 3136,
  "boardHeight390": 3627,
  "sheetUntouched1280": 1113,
  "sheetUntouched390": 1422,
  "sheetHave1280": 1349,
  "sheetHave390": 1680,
  "sheetOpen1280": 1689,
  "sheetOpen390": 2206,
  "sheetOpen1280fr": 1747,
  "sheetOpen390fr": 2201,
  "sheetControls": 15
};
