// Builds share/b-{fr,en}.html from the poster template in designs/b.js and the stylesheet designs/b.css.
import { readFileSync, writeFileSync } from "node:fs";
const HERE = new URL("..", import.meta.url).pathname;
const js = readFileSync(HERE + "designs/b.js", "utf8");
const src = js.split("/*POSTER-START*/")[1].split("/*POSTER-END*/")[0];
const posterHTML = new Function(src + "; return posterHTML;")();
const css = readFileSync(HERE + "designs/b.css", "utf8");
const tokens = css.split("/* ---------- 1. Tokens ---------- */")[1].split("html[data-alt=\"b\"][data-space=\"moteur\"]")[0];
const poster = css.split("/*POSTER-CSS-START*/")[1].split("/*POSTER-CSS-END*/")[0];
for (const lang of ["fr", "en"]) {
  const html = `<!doctype html>
<html lang="${lang}" data-alt="b">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=1200">
<title>${lang === "fr" ? "Tour de Growth — affiche de partage" : "Tour de Growth — share poster"}</title>
<link rel="stylesheet" href="/fonts.css">
<style>
/* Generated by work/mkshare.mjs from designs/b.css (tokens + poster) and designs/b.js (posterHTML). */
${tokens.trim()}
html[data-alt="b"], html[data-alt="b"] body { margin: 0; padding: 0; background: #f3ead3; }
${poster.trim()}
</style>
</head>
<body>
${posterHTML(lang)}
</body>
</html>
`;
  writeFileSync(HERE + `share/b-${lang}.html`, html);
  console.log("wrote", `share/b-${lang}.html`, html.length);
}
