import { METRIC_SHAPES, SLG_METRIC_SHAPES, shapeOf } from "./catalog-shape";
import type { MetricShape } from "./catalog-shape";
import { formatApproxMoneyInterval, formatInterval, formatNumber, roundDisplay, type UnitWords } from "./format";
import { point, sub } from "./interval";
import { lossCheck } from "./money";
import type { PelotonMetric } from "./peloton";
import { slgNoDecimals, smallestSample } from "./relays";
import type {
  CandidateId,
  Comparator,
  DerivedValue,
  EngineCalcContext,
  EngineDerived,
  EngineState,
  Finding,
  Interval,
  MetricId,
  MetricValue,
  Motion,
  MotionDerived,
  Position,
} from "./types";
import { currentSnapshot, entryOf, knownIn, readingValue, statusOf } from "./values";

/**
 * findings.ts — the closed list of things the engine can SAY (engine spec
 * §6.10). A fixed kind, a fixed rank, numbers already formatted, and no
 * text generated by a model.
 *
 * The rule the copy templates are written to: no sentence asserts a CAUSE.
 * "Activation is below its target and onboarding completion isn't
 * tracked" is a finding; "it's the onboarding" is an opinion.
 *
 * An unknown becomes a finding only once someone has looked for it and
 * couldn't find it (`missing`). A number still to do or awaiting a reply is
 * collection in progress, not a fact about the company — it shows in the
 * coverage and the "to go and get" list, never here.
 *
 * `values` carries only formatted NUMBERS. The names the templates also need
 * — a metric's name (`{metric}`, `{input}`), a stage verb (`{verb}`), a
 * source's label (`{sourceA}`) — are copy, resolved by the consumer from
 * `finding.metrics` and the maps below, exactly like every other label.
 */

/** Which `findings.verb.*` a chain break uses — the column's own verb. */
export const CHAIN_VERB: Record<PelotonMetric, "activated" | "d30" | "paid"> = {
  "act.rate": "activated",
  "ret.d30": "d30",
  "rev.paid-conversion": "paid",
};

const RANK: Record<Finding["kind"], Finding["rank"]> = {
  "chain-break": 1,
  // C48: as grave as a missing link — without it, each new customer digs the hole deeper.
  "unit-econ-loss": 1,
  "no-definition": 2,
  "blind-spot": 2,
  "below-comparator": 2,
  "unit-econ-loss-maybe": 2,
  conflict: 3,
  "unit-econ-uncomputable": 3,
  "reconcile-gap": 3,
  "small-cohort": 4,
  "small-sample": 4,
  "hidden-knowledge": 4,
};

/** Order within a rank, so the list is stable across renders and screens. */
const KIND_ORDER = Object.keys(RANK) as Finding["kind"][];

function formatReading(value: MetricValue, id: MetricId, state: EngineState, ctx: EngineCalcContext, words: UnitWords): string {
  const shape = shapeOf(id);
  const v = readingValue(value, shape);
  return v === null ? "" : formatInterval(point(v), shape.unit, ctx, words, { currency: state.setup.currency });
}

/** "20 %" — the team's target, formatted in the metric's unit. */
export function formatComparator(comparator: Comparator, id: MetricId, state: EngineState, ctx: EngineCalcContext, words: UnitWords): string {
  const range: Interval = { lo: comparator.lo, hi: comparator.hi };
  return formatInterval(range, shapeOf(id).unit, ctx, words, { currency: state.setup.currency });
}

/**
 * The findings of the ticked motions, each tagged with its motion (§18.5.8),
 * then sorted: by rank, by kind, and within a kind in canonical order —
 * self-serve's before sales-assisted's, never by a value. The link makes no
 * finding: it is optional, and its absence says nothing about the company.
 */
export function findings(state: EngineState, derived: Omit<EngineDerived, "findings">, ctx: EngineCalcContext, words: UnitWords): Finding[] {
  const snapshot = currentSnapshot(state);
  const out: Finding[] = [];
  const addFor =
    (motion: Motion) =>
    (kind: Finding["kind"], metrics: Finding["metrics"], values: Record<string, string> = {}, count?: Interval) =>
      out.push({ kind, motion, rank: RANK[kind], metrics, values, ...(count ? { count } : {}) });
  const missing = (id: MetricId) => statusOf(entryOf(snapshot, id)) === "missing";

  for (const m of derived.motions) {
    const add = addFor(m.motion);
    if (m.motion === "plg") selfServeFindings(state, m, derived, ctx, words, add, missing);
    else salesAssistedFindings(state, m, ctx, words, add, missing);
  }

  // 2 — declared tracked at the Tour (20 points), and nobody could pull it.
  for (const row of derived.mirror?.rows ?? []) {
    if (row.declared === "tracked" && row.found === "unknown") addFor(row.motion)("blind-spot", [row.metric]);
  }
  // 4 — the positive one: declared unknown at the Tour, and measured here.
  for (const row of derived.mirror?.rows ?? []) {
    if (row.declared === "unknown" && row.found === "tracked") addFor(row.motion)("hidden-knowledge", [row.metric]);
  }

  // Stable: by rank, then by kind; within a kind, the order above (motions in canonical order, then metrics).
  return out
    .map((f, i) => ({ f, i }))
    .sort((a, b) => a.f.rank - b.f.rank || KIND_ORDER.indexOf(a.f.kind) - KIND_ORDER.indexOf(b.f.kind) || a.i - b.i)
    .map(({ f }) => f);
}

type Add = (kind: Finding["kind"], metrics: Finding["metrics"], values?: Record<string, string>, count?: Interval) => void;

/** What a diagnosis named, with its value and the comparator that named it — the same in both motions. */
function namedFindings(
  state: EngineState,
  diagnosis: MotionDerived["diagnosis"],
  ctx: EngineCalcContext,
  words: UnitWords,
  add: Add,
  noDecimals: (id: MetricId) => boolean,
): void {
  if (diagnosis.state !== "clear" && diagnosis.state !== "shared") return;
  const positions = diagnosis.positions as Partial<Record<CandidateId, { position: Position; comparator?: Comparator }>>;
  for (const id of diagnosis.named as CandidateId[]) {
    const comparator = positions[id]?.comparator;
    const known = knownIn(state, id, ctx);
    if (!comparator || known.kind !== "known") continue;
    add("below-comparator", [id], {
      value: formatInterval(known.value, shapeOf(id).unit, ctx, words, { noDecimals: noDecimals(id) }),
      comparator: formatComparator(comparator, id, state, ctx, words),
    });
  }
}

/** Two numbers that disagree, each with its own figure. */
function conflictFindings(state: EngineState, shapes: readonly MetricShape[], ctx: EngineCalcContext, words: UnitWords, add: Add): void {
  const snapshot = currentSnapshot(state);
  for (const shape of shapes) {
    const entry = entryOf(snapshot, shape.id);
    if (entry?.status !== "conflicting" || !entry.conflict) continue;
    add("conflict", [shape.id], {
      a: formatReading(entry.conflict.a.value, shape.id, state, ctx, words),
      b: formatReading(entry.conflict.b.value, shape.id, state, ctx, words),
    });
  }
}

/**
 * The loss (§20.4, C48), on today's LTV and CAC of one motion — never summed
 * across motions. Arithmetic on the team's own numbers: no reference enters
 * it, so it names no stage. The CAC prints as typed (to the unit, or its
 * range), the LTV and the gap as the estimates they are (« ~1 500 € »).
 */
function lossFinding(state: EngineState, ltv: DerivedValue, cacId: "acq.cac" | "slg.acq.cac", ctx: EngineCalcContext, words: UnitWords, add: Add): void {
  const cacKnown = knownIn(state, cacId, ctx);
  if (ltv.kind !== "known" || cacKnown.kind !== "known") return;
  const loss = lossCheck(ltv.value, cacKnown.value);
  if (!loss || loss.verdict === "none") return;
  const currency = state.setup.currency;
  const cac = cacKnown.value;
  const shortfall = sub(cac, ltv.value);
  add(loss.verdict === "loss" ? "unit-econ-loss" : "unit-econ-loss-maybe", [cacId === "acq.cac" ? "rev.ltv" : "slg.rev.ltv", cacId], {
    cac: cac.lo === cac.hi ? formatInterval(cac, "money", ctx, words, { currency }) : formatApproxMoneyInterval(cac, currency, ctx, words),
    ltv: formatApproxMoneyInterval(ltv.value, currency, ctx, words),
    gap: formatApproxMoneyInterval({ lo: Math.max(0, shortfall.lo), hi: Math.max(0, shortfall.hi) }, currency, ctx, words),
  });
}

/** The payback can't be computed, and at least one of its inputs was looked for and not found. */
function paybackFinding(payback: DerivedValue, id: "rev.cac-payback" | "slg.rev.cac-payback", add: Add, missing: (id: MetricId) => boolean): void {
  if (payback.kind === "uncomputable" && payback.missing.some(missing)) add("unit-econ-uncomputable", [id, ...payback.missing]);
}

function selfServeFindings(
  state: EngineState,
  m: Extract<MotionDerived, { motion: "plg" }>,
  derived: Omit<EngineDerived, "findings">,
  ctx: EngineCalcContext,
  words: UnitWords,
  add: Add,
  missing: (id: MetricId) => boolean,
): void {
  const snapshot = currentSnapshot(state);
  const eventMissing = missing("act.event");

  // 1 — a ★ of the peloton that nobody could pull. The activation column breaks too when its EVENT is
  // missing: nobody can count activations of an action nobody has named, and it is said once (§5.3).
  for (const column of m.peloton.columns) {
    if (column.perHundred !== null) continue;
    if (column.metric === "act.rate" && eventMissing) add("chain-break", ["act.event", "act.rate"]);
    else if (missing(column.metric)) add("chain-break", [column.metric]);
  }

  // 2 — no shared definition. Not raised on the rate when its event is already the finding.
  for (const shape of METRIC_SHAPES) {
    if (shape.id === "act.rate" && eventMissing) continue;
    if (entryOf(snapshot, shape.id)?.missing?.cause === "no-definition" && missing(shape.id)) add("no-definition", [shape.id]);
  }

  // 2 — the stages the diagnosis named.
  namedFindings(state, m.diagnosis, ctx, words, add, () => false);

  // 3
  conflictFindings(state, METRIC_SHAPES, ctx, words, add);
  paybackFinding(m.unit.payback, "rev.cac-payback", add, missing);
  lossFinding(state, m.unit.ltv, "acq.cac", ctx, words, add);

  // 3 — the chain and the billing don't describe the same population.
  const gap = derived.sanity.find((c) => c.id === "reconcile-gap");
  if (gap) add("reconcile-gap", gap.metrics, gap.values, gap.count);

  // 4 — each sign-up weighs more than a point.
  if (m.peloton.smallCohort) add("small-cohort", []);
}

/** §18.5.8: the same kinds and ranks, on the relays and the sales-assisted catalogue. */
function salesAssistedFindings(
  state: EngineState,
  m: Extract<MotionDerived, { motion: "slg" }>,
  ctx: EngineCalcContext,
  words: UnitWords,
  add: Add,
  missing: (id: MetricId) => boolean,
): void {
  const snapshot = currentSnapshot(state);
  const liveEventMissing = missing("slg.act.live-event");

  // 1 — a relay nobody could pull. Go-live with no definition of « live » is one finding, on the definition.
  for (const column of m.relays.columns) {
    if (column.perHundred !== null) continue;
    if (column.metric === "slg.act.go-live" && liveEventMissing) add("chain-break", ["slg.act.live-event", "slg.act.go-live"]);
    else if (missing(column.metric)) add("chain-break", [column.metric]);
  }

  // 2 — no shared definition. Not raised on go-live when its definition is already the finding.
  for (const shape of SLG_METRIC_SHAPES) {
    if (shape.id === "slg.act.go-live" && liveEventMissing) continue;
    if (entryOf(snapshot, shape.id)?.missing?.cause === "no-definition" && missing(shape.id)) add("no-definition", [shape.id]);
  }

  namedFindings(state, m.diagnosis, ctx, words, add, (id) => slgNoDecimals(snapshot, id));
  conflictFindings(state, SLG_METRIC_SHAPES, ctx, words, add);
  paybackFinding(m.unit.payback, "slg.rev.cac-payback", add, missing);
  lossFinding(state, m.unit.ltv, "slg.acq.cac", ctx, words, add);

  // 4 — the counted ★ on the smallest base: one more or less moves it by p points (§18.5.1).
  const sample = smallestSample(snapshot);
  if (sample) {
    const p = roundDisplay(sample.points);
    add("small-sample", [sample.metric], { d: formatNumber(sample.denominator, ctx.locale), p: formatInterval(point(sample.points), "ratio", ctx, words) }, point(p));
  }
}
