import { METRIC_SHAPES, shapeOf } from "./catalog-shape";
import { formatInterval, type UnitWords } from "./format";
import { point } from "./interval";
import type { PelotonMetric } from "./peloton";
import type { Comparator, EngineCalcContext, EngineDerived, EngineState, Finding, Interval, MetricId, MetricValue } from "./types";
import { currentSnapshot, entryOf, knownIn, readingValue, statusOf } from "./values";

/**
 * findings.ts — the closed list of things the engine can SAY (engine spec
 * §6.10). A fixed kind, a fixed rank, numbers already formatted, and no
 * text generated by a model.
 *
 * The rule the copy templates are written to: no sentence asserts a CAUSE.
 * "Activation is below its reference and onboarding completion isn't
 * tracked" is a finding; "it's the onboarding" is an opinion.
 *
 * An unknown becomes a finding only once someone has looked for it and
 * couldn't find it (`missing`). A number still to do or awaiting a reply is
 * collection in progress, not a fact about the company — it shows in the
 * coverage and the "to go and get" list, never here.
 *
 * `values` carries only formatted NUMBERS. The names the templates also need
 * — a metric's name (`{metric}`, `{input}`), a stage verb (`{verb}`), a
 * source's label (`{sourceA}`) — are copy, resolved by the consumer from
 * `finding.metrics` and the maps below, exactly like every other label.
 */

/** Which `findings.verb.*` a chain break uses — the column's own verb. */
export const CHAIN_VERB: Record<PelotonMetric, "activated" | "d30" | "paid"> = {
  "act.rate": "activated",
  "ret.d30": "d30",
  "rev.paid-conversion": "paid",
};

const RANK: Record<Finding["kind"], Finding["rank"]> = {
  "chain-break": 1,
  "no-definition": 2,
  "blind-spot": 2,
  "below-comparator": 2,
  conflict: 3,
  "unit-econ-uncomputable": 3,
  "reconcile-gap": 3,
  "small-cohort": 4,
  "hidden-knowledge": 4,
};

/** Order within a rank, so the list is stable across renders and screens. */
const KIND_ORDER = Object.keys(RANK) as Finding["kind"][];

function formatReading(value: MetricValue, id: MetricId, state: EngineState, ctx: EngineCalcContext, words: UnitWords): string {
  const shape = shapeOf(id);
  const v = readingValue(value, shape);
  return v === null ? "" : formatInterval(point(v), shape.unit, ctx, words, { currency: state.setup.currency });
}

/** "20 %" for a target, "20 à 40 %" for a reference — the comparator's own range, formatted in the metric's unit. */
export function formatComparator(comparator: Comparator, id: MetricId, state: EngineState, ctx: EngineCalcContext, words: UnitWords): string {
  const range: Interval = { lo: comparator.lo, hi: comparator.hi };
  return formatInterval(range, shapeOf(id).unit, ctx, words, { currency: state.setup.currency });
}

export function findings(state: EngineState, derived: Omit<EngineDerived, "findings">, ctx: EngineCalcContext, words: UnitWords): Finding[] {
  const snapshot = currentSnapshot(state);
  const out: Finding[] = [];
  const add = (kind: Finding["kind"], metrics: Finding["metrics"], values: Record<string, string> = {}) =>
    out.push({ kind, rank: RANK[kind], metrics, values });
  const missing = (id: MetricId) => statusOf(entryOf(snapshot, id)) === "missing";
  const eventMissing = missing("act.event");

  // 1 — a ★ of the peloton that nobody could pull. The activation column breaks too when its EVENT is
  // missing: nobody can count activations of an action nobody has named, and it is said once (§5.3).
  for (const column of derived.peloton.columns) {
    if (column.perHundred !== null) continue;
    if (column.metric === "act.rate" && eventMissing) add("chain-break", ["act.event", "act.rate"]);
    else if (missing(column.metric)) add("chain-break", [column.metric]);
  }

  // 2 — no shared definition. Not raised on the rate when its event is already the finding.
  for (const shape of METRIC_SHAPES) {
    if (shape.id === "act.rate" && eventMissing) continue;
    if (entryOf(snapshot, shape.id)?.missing?.cause === "no-definition" && missing(shape.id)) add("no-definition", [shape.id]);
  }

  // 2 — declared tracked at the Tour (20 points), and nobody could pull it.
  for (const row of derived.mirror?.rows ?? []) {
    if (row.declared === "tracked" && row.found === "unknown") add("blind-spot", [row.metric]);
  }

  // 2 — the stages the diagnosis named, with their value and the comparator that named them.
  if (derived.diagnosis.state === "clear" || derived.diagnosis.state === "shared") {
    for (const id of derived.diagnosis.named) {
      const comparator = derived.diagnosis.positions[id].comparator;
      const known = knownIn(state, id, ctx);
      if (!comparator || known.kind !== "known") continue;
      add("below-comparator", [id], {
        value: formatInterval(known.value, shapeOf(id).unit, ctx, words),
        comparator: formatComparator(comparator, id, state, ctx, words),
      });
    }
  }

  // 3 — two numbers that disagree, each with its own figure.
  for (const shape of METRIC_SHAPES) {
    const entry = entryOf(snapshot, shape.id);
    if (entry?.status !== "conflicting" || !entry.conflict) continue;
    add("conflict", [shape.id], {
      a: formatReading(entry.conflict.a.value, shape.id, state, ctx, words),
      b: formatReading(entry.conflict.b.value, shape.id, state, ctx, words),
    });
  }

  // 3 — the payback can't be computed, and at least one of its inputs was looked for and not found.
  const payback = derived.unit.payback;
  if (payback.kind === "uncomputable" && payback.missing.some(missing)) add("unit-econ-uncomputable", ["rev.cac-payback", ...payback.missing]);

  // 3 — the chain and the billing don't describe the same population.
  const gap = derived.sanity.find((c) => c.id === "reconcile-gap");
  if (gap) out.push({ kind: "reconcile-gap", rank: RANK["reconcile-gap"], metrics: gap.metrics, values: gap.values, ...(gap.count ? { count: gap.count } : {}) });

  // 4 — each sign-up weighs more than a point.
  if (derived.peloton.smallCohort) add("small-cohort", []);

  // 4 — the positive one: declared unknown at the Tour, and measured here.
  for (const row of derived.mirror?.rows ?? []) {
    if (row.declared === "unknown" && row.found === "tracked") add("hidden-knowledge", [row.metric]);
  }

  // Stable: by rank, then by kind; within a kind, the order above (canonical metric order).
  return out
    .map((f, i) => ({ f, i }))
    .sort((a, b) => a.f.rank - b.f.rank || KIND_ORDER.indexOf(a.f.kind) - KIND_ORDER.indexOf(b.f.kind) || a.i - b.i)
    .map(({ f }) => f);
}
