// Builds designs/ib-ink.css and designs/ib-ink.js from designs/ib.* : the same rules re-prefixed, plus work/ink-diff.css.
import { readFileSync, writeFileSync } from "node:fs";
const HERE = new URL("..", import.meta.url).pathname;
const css = readFileSync(HERE + "designs/ib.css", "utf8").replaceAll('html[data-alt="ib"]', 'html[data-alt="ib-ink"]');
const head = "/* GENERATED by work/mkink.mjs from designs/ib.css — edit ib.css or work/ink-diff.css, not this file. */\n";
writeFileSync(HERE + "designs/ib-ink.css", head + css + readFileSync(HERE + "work/ink-diff.css", "utf8"));
writeFileSync(HERE + "designs/ib-ink.js", "/* GENERATED by work/mkink.mjs: the same decorative DOM as ib.js. */\n" + readFileSync(HERE + "designs/ib.js", "utf8"));
console.log("ib-ink built");
