// Builds share/ib-{fr,en}.html from posterHTML() in designs/ib.js and the tokens + poster block of designs/ib.css.
import { readFileSync, writeFileSync } from "node:fs";
const HERE = new URL("..", import.meta.url).pathname;
const js = readFileSync(HERE + "designs/ib.js", "utf8");
const picto = js.match(/const PICTO = \{[\s\S]*?\n  \};/)[0];
const src = js.split("/*POSTER-START*/")[1].split("/*POSTER-END*/")[0];
const posterHTML = new Function(picto + "\n" + src + "; return posterHTML;")();
const css = readFileSync(HERE + "designs/ib.css", "utf8");
const grain = css.match(/--ib-grain: (url\([^\n]*\));/)[1];
const poster = css.split("/*POSTER-CSS-START*/")[1].split("/*POSTER-CSS-END*/")[0];
for (const lang of ["fr", "en"]) {
  const html = `<!doctype html>
<html lang="${lang}" data-alt="ib">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=1200">
<title>${lang === "fr" ? "Tour de Growth — image de partage" : "Tour de Growth — share image"}</title>
<link rel="stylesheet" href="/fonts.css">
<style>
/* Generated by work/mkshare-ib.mjs from designs/ib.css (poster block) and designs/ib.js (posterHTML). */
html[data-alt="ib"] { --ib-grain: ${grain}; }
html, body { margin: 0; padding: 0; background: #ebe5d7; }
${poster.trim()}
</style>
</head>
<body>
${posterHTML(lang)}
</body>
</html>
`;
  writeFileSync(HERE + `share/ib-${lang}.html`, html);
  console.log("wrote", `share/ib-${lang}.html`, html.length);
}
