import type { LevelSlug } from "@/lib/game/types";
import type { Translatable } from "@/lib/i18n/translatable";

/**
 * entry.ts — the card that offers the game on a result page (GAME-BRIEF.md
 * 13.3 A, plan §3.10 and §2.6 `GameEntry`).
 *
 * **TODO: à relire** (convention 6). The title, the two opening sentences,
 * the body, the button and the mention are the brief's own text (13.3),
 * French and English; the brief itself says they are to be reread before
 * anything goes live. The band's three labels are new copy written by the
 * code session, reusing the words the level's dashboard already says
 * (`content/game/retention.ts`, `dashboard.churn` and
 * `dashboard.notOnDashboard`).
 *
 * Its own module, and only the result page imports it: the level's text
 * (`retention.ts`, ~800 lines) must not ride into the result page's server
 * function to render one card (content-fan-in.test.ts, budget 1).
 *
 * Keyed by level rather than written flat: the table pilier → niveau
 * (`GAME_LEVELS_BY_PILLAR`) will grow, and the card for a new level is then a
 * new entry here — `satisfies Record<LevelSlug, …>` fails to compile until it
 * exists.
 *
 * Nothing in the card is ever generated by Gemini (13.3, variante Deep dive):
 * the only thing a Deep dive changes is which opening sentence is used.
 */
const t = (fr: string, en: string): Translatable => ({ fr, en });

export interface GameEntryCopy {
  title: Translatable;
  /** The card's first sentence — which one depends on whether the result carries a Deep dive. */
  opening: { result: Translatable; deepDive: Translatable };
  /** Everything after the first sentence. */
  body: Translatable;
  cta: Translatable;
  /** The mono mention beside the button. */
  meta: Translatable;
  /**
   * The night band across the top of the card: the object of the game in one
   * glance — the one number the CEO watches, and the one that is missing from
   * his dashboard. `{churn}` is the level's starting churn, formatted by the
   * caller from the level model rather than written here, so the card cannot
   * quote a number the game does not start from.
   */
  band: {
    churn: Translatable;
    trust: Translatable;
    notOnDashboard: Translatable;
  };
}

export const GAME_ENTRY_COPY = {
  retention: {
    title: t("Le côté obscur de la rétention", "The dark side of retention"),
    opening: {
      result: t("Tu sais maintenant quoi faire.", "Now you know what to do."),
      deepDive: t("Tes recommandations sont au-dessus.", "Your recommendations are above."),
    },
    body: t(
      "Voici ce qu'il ne faut pas faire : joue une année comme PM growth d'une appli de streaming, un DG qui veut du chiffre, et huit astuces que tu reconnaîtras ensuite partout.",
      "Here is what not to do: play a year as the growth PM of a streaming app, with a CEO who wants the number, and eight tricks you will recognise everywhere afterwards.",
    ),
    cta: t("Jouer le niveau « S'ils reviennent »", 'Play the level "If they come back"'),
    meta: t("vingt minutes, gratuit", "twenty minutes, free"),
    band: {
      churn: t("Résiliations {churn}", "Churn {churn}"),
      trust: t("Confiance", "Trust"),
      notOnDashboard: t("pas sur ton dashboard", "not on your dashboard"),
    },
  },
} as const satisfies Record<LevelSlug, GameEntryCopy>;
