// Embeds the H share images (shots/h/share-{fr,en}.png) into designs/h.css so the
// result page's share preview shows this direction's image, not today's.
const sharp = require("/home/user/tourdegrowth/node_modules/sharp");
const fs = require("fs");
const path = require("path");
const ALT = path.join(__dirname, "..");
(async () => {
  let block = "/* @h-share-start — generated by .h/embed-share.cjs from share/h-{fr,en}.html */\n";
  for (const lang of ["fr", "en"]) {
    const buf = await sharp(path.join(ALT, "shots/h", `share-${lang}.png`)).resize(760).jpeg({ quality: 84, mozjpeg: true }).toBuffer();
    block += `html[data-alt="h"][lang="${lang}"] .ShareCard--image {\n  content: url("data:image/jpeg;base64,${buf.toString("base64")}");\n}\n`;
    console.log(lang, buf.length);
  }
  block += "/* @h-share-end */\n";
  const cssPath = path.join(ALT, "designs/h.css");
  let css = fs.readFileSync(cssPath, "utf8");
  css = css.replace(/\/\* @h-share-start[\s\S]*?@h-share-end \*\/\n/, "");
  fs.writeFileSync(cssPath, css.trimEnd() + "\n\n" + block);
})();
